version: '3'

services:
  database:
    image: mysql:latest
    container_name: 'mysql_container'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vehicle_db

#  mailhog:
#    image: mailhog/mailhog
#    container_name: 'mailhog'
#    ports:
#      - "1025:1025"
#      - "8025:8025"